services:
  spark-job:
      build: .
      container_name: spark-job
      volumes:
        - ./:/app:ro
        - ./jars:/opt/jars:ro
      entrypoint: ["spark-submit"]
      command: [
        "--master", "spark://spark-master:7077",
        "/app/etl/spark_jobs/build_reports.py"
      ]
      networks:
        - shared